### ISSUE TITLE
Add suppression annotation for a specific instance of an exclusionary term

### ISSUE THREAD

**Issue by devstuff** [zendesk/term-check#19]
Rather than excluding an entire file (see #16), I would like to be able to add suppression annotations in a file to explicitly suppress the warning, say for backward compatibility.

As an example, I have a configuration file that includes both `account-replica-urls` (the new inclusionary and preferred setting) and `account-slave-urls` (only for backwards compatibility). To explicitly exclude the compatibility setting from generating warnings, the line before would be a comment line containing the annotation:

```
account-replica-urls = "whatever"
// $$TERM_CHECK_IGNORE$$ This setting is for backward compatibility
account-slave-urls = "whatever"
```

Everything on the line outside the annotation pattern (`$$TERM_CHECK_IGNORE$$`) is ignored.

The file reader would have to cache the previous line to compare it against the pattern if a term is found on the current line.

**Comment by ragurney** [comment]
I like it, and would prefer to follow a well-known format such as [eslint's](https://eslint.org/docs/user-guide/configuring#disabling-rules-with-inline-comments). However, this might mean we need to change how the bot behaves. Right now, it only scans the added lines in a Pull Request, so diffs such as:
```diff
// term-check-disable-next-line
- some_func_slave
+ func_slave
```

or

```diff
// term-check-disable
- master
+ slave
// term-check-enable
```

would not behave as expected, and would cause those added terms to be flagged. We could either: 
1. Change the bot logic so that it scans whole files that are changed instead of just the added lines.
2. Only support single, inline annotations per e.g. `// term-check-disable-line`.

What do you think?
